/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.GUI;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sk.stu.fiit.Controllers.IMethod;

/**
 *
 * @author Acer
 */
public class ReferentWindow extends javax.swing.JFrame {

    /**
     * Creates new form ReferentWindow
     */
    public ReferentWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pLogin = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnGoodsOverview = new javax.swing.JButton();
        btnCosts = new javax.swing.JButton();
        btnProfits = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        lbUsername = new javax.swing.JLabel();
        pGoodsOverview = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOverviewGoods = new javax.swing.JTable();
        lbTotalPrice = new javax.swing.JLabel();
        pGoodsCosts = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnViewCosts = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbCosts = new javax.swing.JLabel();
        ftfCostsFrom = new javax.swing.JFormattedTextField();
        ftfCostsTo = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbGoodsCosts = new javax.swing.JTable();
        pGoodsProfits = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnViewProfits = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbProfits = new javax.swing.JLabel();
        ftfProfitsFrom = new javax.swing.JFormattedTextField();
        ftfProfitsTo = new javax.swing.JFormattedTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbGoodsProfits = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        miChangePassword = new javax.swing.JMenuItem();
        miLogout = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miGoodsOverview = new javax.swing.JMenuItem();
        miCosts = new javax.swing.JMenuItem();
        miProfits = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 1000));
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        pLogin.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnGoodsOverview.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnGoodsOverview.setText("Prehľad tovarov");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        jPanel4.add(btnGoodsOverview, gridBagConstraints);

        btnCosts.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnCosts.setText("Zobrazenie nákladov");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        jPanel4.add(btnCosts, gridBagConstraints);

        btnProfits.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnProfits.setText("Zobrazenie ziskov");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        jPanel4.add(btnProfits, gridBagConstraints);

        pLogin.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        lbName.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lbName.setText("Meno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        jPanel5.add(lbName, gridBagConstraints);

        btnLogout.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnLogout.setText("Odhlásiť sa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        jPanel5.add(btnLogout, gridBagConstraints);

        btnChangePassword.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnChangePassword.setText("Zmeniť heslo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        jPanel5.add(btnChangePassword, gridBagConstraints);

        lbUsername.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lbUsername.setText("Prihlasovacie meno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        jPanel5.add(lbUsername, gridBagConstraints);

        pLogin.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(pLogin, "card2");

        pGoodsOverview.setBackground(new java.awt.Color(255, 255, 255));
        pGoodsOverview.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabel1.setText("Prehľad tovarov");
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 41));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsOverview.add(jLabel1, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 500));

        tbOverviewGoods.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tbOverviewGoods.getTableHeader().setFont(new java.awt.Font("Arial", 1, 15));
        tbOverviewGoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kód tovaru", "Názov tovaru", "Množstvo", "Nákupná cena", "Predajná cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbOverviewGoods);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsOverview.add(jScrollPane1, gridBagConstraints);

        lbTotalPrice.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        lbTotalPrice.setText("Celková cena skladovaného tovaru:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsOverview.add(lbTotalPrice, gridBagConstraints);

        jPanel1.add(pGoodsOverview, "card3");

        pGoodsCosts.setBackground(new java.awt.Color(255, 255, 255));
        pGoodsCosts.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setText("Dátum od:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 300);
        pGoodsCosts.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel3.setText("Dátum do:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 300);
        pGoodsCosts.add(jLabel3, gridBagConstraints);

        btnViewCosts.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnViewCosts.setText("Zobraziť náklady");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsCosts.add(btnViewCosts, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabel4.setText("Prehľad celkových nákladov za zvolené obdobie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsCosts.add(jLabel4, gridBagConstraints);

        lbCosts.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        lbCosts.setText("Celkové náklady za zvolené obdobie:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsCosts.add(lbCosts, gridBagConstraints);

        ftfCostsFrom.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ftfCostsFrom.setMinimumSize(new java.awt.Dimension(250, 28));
        ftfCostsFrom.setPreferredSize(new java.awt.Dimension(250, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(25, 300, 25, 25);
        pGoodsCosts.add(ftfCostsFrom, gridBagConstraints);

        ftfCostsTo.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ftfCostsTo.setMinimumSize(new java.awt.Dimension(250, 28));
        ftfCostsTo.setPreferredSize(new java.awt.Dimension(250, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 300, 25, 25);
        pGoodsCosts.add(ftfCostsTo, gridBagConstraints);

        jScrollPane3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jScrollPane3.setMinimumSize(new java.awt.Dimension(800, 500));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(1000, 500));

        tbGoodsCosts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kód tovaru", "Názov tovaru", "Množstvo", "Príjmová cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbGoodsCosts);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsCosts.add(jScrollPane3, gridBagConstraints);

        jPanel1.add(pGoodsCosts, "card4");

        pGoodsProfits.setBackground(new java.awt.Color(255, 255, 255));
        pGoodsProfits.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel5.setText("Dátum od:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 300);
        pGoodsProfits.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel6.setText("Dátum do:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 300);
        pGoodsProfits.add(jLabel6, gridBagConstraints);

        btnViewProfits.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnViewProfits.setText("Zobraziť zisky");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsProfits.add(btnViewProfits, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabel7.setText("Prehľad celkových ziskov za zvolené obdobie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsProfits.add(jLabel7, gridBagConstraints);

        lbProfits.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        lbProfits.setText("Celkové zisky za zvolené obdobie:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsProfits.add(lbProfits, gridBagConstraints);

        ftfProfitsFrom.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ftfProfitsFrom.setMinimumSize(new java.awt.Dimension(250, 28));
        ftfProfitsFrom.setPreferredSize(new java.awt.Dimension(250, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(25, 300, 25, 25);
        pGoodsProfits.add(ftfProfitsFrom, gridBagConstraints);

        ftfProfitsTo.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ftfProfitsTo.setMinimumSize(new java.awt.Dimension(250, 28));
        ftfProfitsTo.setPreferredSize(new java.awt.Dimension(250, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(25, 300, 25, 25);
        pGoodsProfits.add(ftfProfitsTo, gridBagConstraints);

        jScrollPane4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jScrollPane4.setMinimumSize(new java.awt.Dimension(800, 500));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(1000, 500));

        tbGoodsProfits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kód tovaru", "Názov tovaru", "Množstvo", "Príjmová cena", "Vývozná cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbGoodsProfits);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        pGoodsProfits.add(jScrollPane4, gridBagConstraints);

        jPanel1.add(pGoodsProfits, "card4");

        getContentPane().add(jPanel1);

        jMenu3.setText("Správa účtu");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        miChangePassword.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        miChangePassword.setText("Zmena hesla");
        jMenu3.add(miChangePassword);

        miLogout.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        miLogout.setText("Odhlásiť sa");
        jMenu3.add(miLogout);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Zobrazenie");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        miGoodsOverview.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        miGoodsOverview.setText("Prehľad tovarov");
        jMenu1.add(miGoodsOverview);

        miCosts.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        miCosts.setText("Zobraziť náklady");
        jMenu1.add(miCosts);

        miProfits.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        miProfits.setText("Zobraziť zisky");
        jMenu1.add(miProfits);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnCosts;
    private javax.swing.JButton btnGoodsOverview;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfits;
    private javax.swing.JButton btnViewCosts;
    private javax.swing.JButton btnViewProfits;
    private javax.swing.JFormattedTextField ftfCostsFrom;
    private javax.swing.JFormattedTextField ftfCostsTo;
    private javax.swing.JFormattedTextField ftfProfitsFrom;
    private javax.swing.JFormattedTextField ftfProfitsTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbCosts;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbProfits;
    private javax.swing.JLabel lbTotalPrice;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JMenuItem miChangePassword;
    private javax.swing.JMenuItem miCosts;
    private javax.swing.JMenuItem miGoodsOverview;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miProfits;
    private javax.swing.JPanel pGoodsCosts;
    private javax.swing.JPanel pGoodsOverview;
    private javax.swing.JPanel pGoodsProfits;
    private javax.swing.JPanel pLogin;
    private javax.swing.JTable tbGoodsCosts;
    private javax.swing.JTable tbGoodsProfits;
    private javax.swing.JTable tbOverviewGoods;
    // End of variables declaration//GEN-END:variables

    public void changePasswordListener(IMethod iMethod) {
        btnChangePassword.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                iMethod.method();
            }
        });
        miChangePassword.addActionListener(e -> iMethod.method());
    }
    
    public void costsListener(IMethod iMethod) {
        btnCosts.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                iMethod.method();
            }
        });
        miCosts.addActionListener(e -> iMethod.method());
    }
    
    public void profitsListener(IMethod iMethod) {
        btnProfits.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                iMethod.method();
            }
        });
        miProfits.addActionListener(e -> iMethod.method());
    }
    
    public void goodsOverviewListener(IMethod iMethod) {
        btnGoodsOverview.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                iMethod.method();
            }
        });
        miGoodsOverview.addActionListener(e -> iMethod.method());
    }

    public void logoutListener(IMethod iMethod) {
        btnLogout.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                iMethod.method();
            }
        });
        miLogout.addActionListener(e -> iMethod.method());
    }

    public JPanel getpLogin() {
        return pLogin;
    }

    public DefaultTableModel getTbOverviewGoodsModel() {
        return (DefaultTableModel) tbOverviewGoods.getModel();
    }

    public void setLbTotalPrice(String text) {
        this.lbTotalPrice.setText("Celková cena skladovaného tovaru: " + text);
    }

    public void btnViewCostsAddListener(MouseAdapter adapter) {
        btnViewCosts.addMouseListener(adapter);
    }

    public String getFtfCostsFrom() {
        return ftfCostsFrom.getText().trim();
    }

    public void setFtfCostsFrom(String text) {
        ftfCostsFrom.setText(text);
    }
    
    public String getFtfCostsTo() {
        return ftfCostsTo.getText().trim();
    }
    
    public void setFtfCostsTo(String text) {
        ftfCostsTo.setText(text);
    }

    public void setLbCosts(String text) {
        lbCosts.setText("Celkové náklady za zvolené obdobie: " + text);
    }

    public DefaultTableModel getTbGoodsCosts() {
        return (DefaultTableModel) tbGoodsCosts.getModel();
    }

    public JPanel getpGoodsCosts() {
        return pGoodsCosts;
    }

    public JPanel getpGoodsOverview() {
        return pGoodsOverview;
    }

    public void btnViewProfitsAddListener(MouseAdapter adapter) {
        btnViewProfits.addMouseListener(adapter);
    }

    public String getFtfProfitsFrom() {
        return ftfProfitsFrom.getText().trim();
    }

    public String getFtfProfitsTo() {
        return ftfProfitsTo.getText().trim();
    }

    public void setLbProfits(String text) {
        lbProfits.setText("Celkové zisky za zvolené obdobie: " + text);
    }

    public JPanel getpGoodsProfits() {
        return pGoodsProfits;
    }

    public DefaultTableModel getTbGoodsProfits() {
        return (DefaultTableModel) tbGoodsProfits.getModel();
    }

    
    
    
    public void removeListeners() {
        //Login panel ??
        for (MouseListener ml : btnLogout.getMouseListeners()) {
            btnLogout.removeMouseListener(ml);
        }
        for (MouseListener ml : btnChangePassword.getMouseListeners()) {
            btnChangePassword.removeMouseListener(ml);
        }
        
        //GoodsCosts panel
        for (MouseListener ml : btnViewCosts.getMouseListeners()) {
            btnViewCosts.removeMouseListener(ml);
        }
        
        //GoodsProfits panel
        for (MouseListener ml : btnViewProfits.getMouseListeners()) {
            btnViewProfits.removeMouseListener(ml);
        }
    }
    
}
